Add support for APOD understanding the current date
kaylimepy/echo pull request #1
Opened 2023-07-24 21:11 UTC by rbeasse

Also allow Echo to grab historical APOD images

2023-07-24 22:15 UTC, kaylimepy commented on lib/gpt.py
> +    function_map = {'get_apod': get_apod}
Thank you. Way cleaner.

2023-07-24 22:17 UTC, kaylimepy commented on lib/gpt.py
> +        return function_map[function_name](date=function_args.get('date'))
Noice!

2023-07-24 22:29 UTC, kaylimepy requested changes
This is looking great! Thanks for these updates. Excited to see what Echo's future brings.

2023-07-24 22:29 UTC, kaylimepy commented on lib/gpt.py
> +        return function_map[function_name](date=function_args.get('date'))
Actually maybe for consistency we should use use `[date]` instead of get as it is a required parameter. The if statement above should maybe be:

`if 'function_call' in response_message:`

What do you think?

2023-07-24 22:29 UTC, kaylimepy commented on lib/gpt.py
> +    # to add it to the historical messages.
What do you mean by 'historical messages'?

2023-07-24 22:29 UTC, kaylimepy commented on lib/gpt.py
> +    current_date = f'Todays date is {datetime.now().strftime("%d/%m/%Y")}. Use this date for any date related questions.'
Smart prompt! 💯

2023-07-25 00:54 UTC, rbeasse commented on lib/gpt.py
> +        return function_map[function_name](date=function_args.get('date'))
I agree. Made changes to reflect.

2023-07-25 00:54 UTC, rbeasse commented on lib/gpt.py
> +    # to add it to the historical messages.
Typo! Fixed!

2023-07-25 21:06 UTC, merged